In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [ ]:
indian = pd.read_excel("D:\\SevenMentor\\ML\\workspace\\Dataset\\Indian_Economy_Sectorwise_Dataset.xlsx")

In [ ]:
indian

     Year Quarter                 Sector  ...  CPI  IIP  Tax_Revenue_Crore
0    2015      Q1            Agriculture  ...  163   95             123957
1    2015      Q1          Manufacturing  ...  121   88             184005
2    2015      Q1           Construction  ...  114  115             198671
3    2015      Q1                 Mining  ...  158  100              91599
4    2015      Q1            Electricity  ...  130  131             266982
..    ...     ...                    ...  ...  ...  ...                ...
655  2025      Q4              Transport  ...  131  130             231228
656  2025      Q4                Tourism  ...  162  115             113273
657  2025      Q4            Real Estate  ...  173  102             171306
658  2025      Q4          Communication  ...  161   86             131980
659  2025      Q4  Public Administration  ...  162  108             135266

[660 rows x 13 columns]

In [ ]:
len(indian.Sector.unique())

15

In [ ]:
indian["GNP"] = indian["GDP_Lakh_Crore"] + indian["Imports_Crore"] - indian["Exports_Crore"]

# now encoding on string data

In [ ]:
e = LabelEncoder()

In [ ]:
indian["Sector_en"] = e.fit_transform(indian.Sector)

In [ ]:
indian["Quarter_en"] = e.fit_transform(indian.Quarter)

In [ ]:
indian.drop(columns=["Quarter", "Sector"], inplace=True)

# minmax scalar in string

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
m = MinMaxScaler()

In [ ]:
indian.Sector_en

0       0
1       8
2       2
3       9
4       4
       ..
655    14
656    13
657    11
658     1
659    10
Name: Sector_en, Length: 660, dtype: int64

In [ ]:
indian["Sector_min_max"] = m.fit_transform(indian[["Sector_en"]])

In [ ]:
indian["Gdp_min_max"] = m.fit_transform(indian[["GDP_Lakh_Crore"]])
indian["Growth_%_min_max"] = m.fit_transform(indian[["Growth_%"]])
indian["GNP_%_min_max"] = m.fit_transform(indian[["GNP"]])

In [ ]:
indian

     Year  GDP_Lakh_Crore  ...  Growth_%_min_max  GNP_%_min_max
0    2015           29.72  ...          0.494975       0.607156
1    2015           37.35  ...          0.990787       0.699242
2    2015           64.71  ...          0.668342       0.779977
3    2015           30.02  ...          0.963149       0.572052
4    2015           50.47  ...          0.981575       0.539950
..    ...             ...  ...               ...            ...
655  2025           72.13  ...          0.199330       0.605927
656  2025           44.45  ...          0.041039       0.516567
657  2025           41.92  ...          0.399497       0.161066
658  2025           63.20  ...          0.319933       0.348925
659  2025           69.16  ...          0.392797       0.141463

[660 rows x 18 columns]

In [ ]:
indian["GNP_%_min_max"]

0      0.607156
1      0.699242
2      0.779977
3      0.572052
4      0.539950
         ...
655    0.605927
656    0.516567
657    0.161066
658    0.348925
659    0.141463
Name: GNP_%_min_max, Length: 660, dtype: float64

# binerization

In [ ]:
from sklearn.preprocessing import Binarizer

In [ ]:
bine = Binarizer(threshold=2020)

In [ ]:
indian["Year"] = bine.fit_transform(indian[["Year"]])

In [ ]:
indian

     Year  GDP_Lakh_Crore  ...  Growth_%_min_max  GNP_%_min_max
0       0           29.72  ...          0.494975       0.607156
1       0           37.35  ...          0.990787       0.699242
2       0           64.71  ...          0.668342       0.779977
3       0           30.02  ...          0.963149       0.572052
4       0           50.47  ...          0.981575       0.539950
..    ...             ...  ...               ...            ...
655     1           72.13  ...          0.199330       0.605927
656     1           44.45  ...          0.041039       0.516567
657     1           41.92  ...          0.399497       0.161066
658     1           63.20  ...          0.319933       0.348925
659     1           69.16  ...          0.392797       0.141463

[660 rows x 18 columns]

# Split data into train and test

In [ ]:
from sklearn.model_selection import train_test_split

X = indian.drop("Year", axis = 1) # store featuer data in "X"
y = indian["Year"] # store target in "y"

In [ ]:
X

     GDP_Lakh_Crore  Growth_%  ...  Growth_%_min_max  GNP_%_min_max
0             29.72      3.94  ...          0.494975       0.607156
1             37.35      9.86  ...          0.990787       0.699242
2             64.71      6.01  ...          0.668342       0.779977
3             30.02      9.53  ...          0.963149       0.572052
4             50.47      9.75  ...          0.981575       0.539950
..              ...       ...  ...               ...            ...
655           72.13      0.41  ...          0.199330       0.605927
656           44.45     -1.48  ...          0.041039       0.516567
657           41.92      2.80  ...          0.399497       0.161066
658           63.20      1.85  ...          0.319933       0.348925
659           69.16      2.72  ...          0.392797       0.141463

[660 rows x 17 columns]

In [ ]:
y

0      0
1      0
2      0
3      0
4      0
      ..
655    1
656    1
657    1
658    1
659    1
Name: Year, Length: 660, dtype: int64

### Split data in x_train, x_test & y_train, y_test

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

In [ ]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:",y_train.shape)
print("y_test:", y_test.shape)

X_train: (528, 17)
X_test: (132, 17)
y_train: (528,)
y_test: (132,)

In [ ]:
indian.columns

Index(['Year', 'GDP_Lakh_Crore', 'Growth_%', 'Employment_Million',
       'Exports_Crore', 'Imports_Crore', 'FDI_Crore', 'Inflation_%', 'CPI',
       'IIP', 'Tax_Revenue_Crore', 'GNP', 'Sector_en', 'Quarter_en',
       'Sector_min_max', 'Gdp_min_max', 'Growth_%_min_max', 'GNP_%_min_max'],
      dtype='str')

In [ ]:
Index(['GDP_Lakh_Crore', 'Growth_%', 'Employment_Million', 'Exports_Crore',
       'Imports_Crore', 'FDI_Crore', 'Inflation_%', 'CPI', 'IIP',
       'Tax_Revenue_Crore', 'GNP', 'Quarter_New', 'Sector_New', 'Year_New'],
      dtype='object')