In [11]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, LabelBinarizer, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [12]:
sales = pd.read_excel(r"D:\SevenMentor\ML\workspace\Dataset\Sales_Data_Cleaned (1).xlsx")

In [13]:
sales

,Customer ID,Customer Name,Region,Product Category,Quantity,Selling Price,Purchase Date
0,CUST1000,Rahul Gupta,North,Toys & Games,39,10710.57,03-12-2024
1,CUST1001,Aarav Joshi,North,Electronics,29,12171.09,22-11-2024
2,CUST1002,Ayaan Mehta,East,Apparel,15,5327.69,04-04-2025
3,CUST1003,Arjun Gupta,South,Home & Kitchen,43,1578.22,07-02-2025
4,CUST1004,Amit Shetty,South,Grocery,8,14116.77,15-01-2025
...,...,...,...,...,...,...,...
245,CUST1245,Rohit Mehta,North,Footwear,29,9096.25,26-01-2025
246,CUST1246,Krishna Nair,West,Footwear,3,8372.49,28-11-2024
247,CUST1247,Rohit Gupta,Central,Home & Kitchen,20,3309.01,01-04-2025
248,CUST1248,Aadhya Verma,North,Toys & Games,36,14200.99,26-01-2025
249,CUST1249,Pooja Malhotra,North,Footwear,19,11752.25,31-01-2025

In [14]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer ID       250 non-null    str
 1   Customer Name     250 non-null    str
 2   Region            250 non-null    str
 3   Product Category  250 non-null    str
 4   Quantity          250 non-null    int64
 5   Selling Price     250 non-null    float64
 6   Purchase Date     250 non-null    str
dtypes: float64(1), int64(1), str(5)
memory usage: 13.8 KB

In [15]:
sales["Product Category"].unique()

<StringArray>
[          'Toys & Games',            'Electronics',                'Apparel',
         'Home & Kitchen',                'Grocery',              'Furniture',
               'Footwear', 'Beauty & Personal Care',      'Health & Wellness',
                  'Books']
Length: 10, dtype: str

In [16]:
sales = sales.drop(columns = ["Customer ID", "Customer Name", "Quantity", "Purchase Date"])

In [17]:
sales

      Region Product Category  Selling Price
0      North     Toys & Games       10710.57
1      North      Electronics       12171.09
2       East          Apparel        5327.69
3      South   Home & Kitchen        1578.22
4      South          Grocery       14116.77
..       ...              ...            ...
245    North         Footwear        9096.25
246     West         Footwear        8372.49
247  Central   Home & Kitchen        3309.01
248    North     Toys & Games       14200.99
249    North         Footwear       11752.25

[250 rows x 3 columns]

In [18]:
le_1 = LabelEncoder()
le_2 = LabelEncoder()

In [19]:
sales["Region"] = le_1.fit_transform(sales["Region"])
sales["Product Category"] = le_2.fit_transform(sales["Product Category"])

In [20]:
sales["Region"]

0      2
1      2
2      1
3      3
4      3
      ..
245    2
246    4
247    0
248    2
249    2
Name: Region, Length: 250, dtype: int64

In [21]:
me_1 = MinMaxScaler()
me_2 = MinMaxScaler()
me_3 = MinMaxScaler()

In [22]:
sales["Region"] = me_1.fit_transform(sales[["Region"]])
sales["Product Category"] = me_2.fit_transform(sales[["Product Category"]])
sales["Selling Price"] = me_3.fit_transform(sales[["Selling Price"]])

In [23]:
sales

     Region  Product Category  Selling Price
0      0.50          1.000000       0.712326
1      0.50          0.333333       0.811564
2      0.25          0.000000       0.346576
3      0.75          0.888889       0.091811
4      0.75          0.666667       0.943767
..      ...               ...            ...
245    0.50          0.444444       0.602638
246    1.00          0.444444       0.553461
247    0.00          0.888889       0.209413
248    0.50          1.000000       0.949490
249    0.50          0.444444       0.783105

[250 rows x 3 columns]

In [24]:
x = sales.drop(["Selling Price"], axis = 1)
y = sales["Selling Price"]

In [25]:
# split 

x_trian, x_test, y_trian, y_test = train_test_split(x, y, test_size = 0.2, shuffle = True, random_state = 42 )

In [26]:
model = LinearRegression()

In [27]:
x_test

     Region  Product Category
142    0.00          0.222222
6      0.50          0.444444
97     0.75          0.111111
60     0.75          0.888889
112    1.00          0.333333
181    0.75          1.000000
197    0.00          0.555556
184    0.25          0.222222
9      0.00          0.555556
104    0.00          0.777778
200    0.50          0.000000
216    1.00          0.222222
236    0.75          0.333333
240    1.00          0.555556
67     0.25          0.444444
224    0.25          0.111111
194    0.00          0.555556
15     0.75          0.111111
177    0.00          0.111111
24     1.00          0.888889
247    0.00          0.888889
19     0.00          1.000000
114    0.50          0.555556
68     0.25          0.222222
176    0.00          0.222222
45     0.00          0.555556
55     0.50          0.777778
10     1.00          0.333333
30     0.25          0.333333
120    0.50          0.111111
201    0.50          0.555556
33     0.75          0.444444
141    0.75          0.333333
219    1.00          1.000000
25     0.00          0.333333
111    0.00          0.111111
18     0.50          0.555556
196    0.75          0.222222
180    0.00          0.222222
159    0.25          0.888889
118    1.00          0.222222
96     1.00          0.666667
108    0.25          0.111111
185    1.00          0.333333
222    0.50          0.222222
16     0.00          0.444444
146    0.00          0.222222
69     0.75          0.000000
173    0.00          0.333333
38     0.50          1.000000

In [28]:
model.fit(x_trian, y_trian)

LinearRegression()

In [29]:
model.coef_

array([0.00747746, 0.06757405])

In [30]:
model.intercept_

np.float64(0.45867877241997773)

In [31]:
x_test_Region = me_1.inverse_transform(x_test[["Region"]])
x_test_Product_Category = me_2.inverse_transform(x_test[["Product Category"]])
# x_test_Region = me_1.inverse_transform(x_test[["Region"]])

In [32]:
x_test_Region

array([[0.],
       [2.],
       [3.],
       [3.],
       [4.],
       [3.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [4.],
       [3.],
       [4.],
       [1.],
       [1.],
       [0.],
       [3.],
       [0.],
       [4.],
       [0.],
       [0.],
       [2.],
       [1.],
       [0.],
       [0.],
       [2.],
       [4.],
       [1.],
       [2.],
       [2.],
       [3.],
       [3.],
       [4.],
       [0.],
       [0.],
       [2.],
       [3.],
       [0.],
       [1.],
       [4.],
       [4.],
       [1.],
       [4.],
       [2.],
       [0.],
       [0.],
       [3.],
       [0.],
       [2.]])

In [33]:
x_test_Product_Category

array([[2.],
       [4.],
       [1.],
       [8.],
       [3.],
       [9.],
       [5.],
       [2.],
       [5.],
       [7.],
       [0.],
       [2.],
       [3.],
       [5.],
       [4.],
       [1.],
       [5.],
       [1.],
       [1.],
       [8.],
       [8.],
       [9.],
       [5.],
       [2.],
       [2.],
       [5.],
       [7.],
       [3.],
       [3.],
       [1.],
       [5.],
       [4.],
       [3.],
       [9.],
       [3.],
       [1.],
       [5.],
       [2.],
       [2.],
       [8.],
       [2.],
       [6.],
       [1.],
       [3.],
       [2.],
       [4.],
       [2.],
       [0.],
       [3.],
       [9.]])

In [34]:
x_test_Region = le_1.inverse_transform(x_test_Region.astype(int))
# x_test_Region = le_2.inverse_transform(x_test_Product_Category)

d:\SevenMentor\ML\workspace\.ml_work\Lib\site-packages\sklearn\preprocessing\_label.py:161: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [35]:
x_test_value

NameError: name 'x_test_value' is not defined

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
mse = mean_squared_error(y_test, y_pred)
mar = mean_absolute_error(y_test, y_pred)

In [36]:
mes

NameError: name 'mes' is not defined

In [ ]:
mar