y=mx+c

y=m1x1+m2x2+m3x3+ .. +mnXn

m -- >slope

x1=1000

88%

...

What is Gradient Descent?

Gradient descent is an optimization algorithm used in ML to find
the best fit parameters of a model by minimizing the error(loss/cost function)

In [1]:
import pandas as pd
from math import nan

In [2]:
df = pd.DataFrame({
    "Name":["Amit", None, "Amit", "Snehal"],
    "Age":[25,25, None,28]
})

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      float64
dtypes: float64(1), str(1)
memory usage: 196.0 bytes

In [4]:
df.isnull().sum()

Name    1
Age     1
dtype: int64

In [5]:
# # fillining null value in continous data
# x = df["Age"].mean()
# df["Age"] = df["Age"].fillna(x)

# # filling null value in categrical data

# y = df["Name"].mode()[0]
# df["Name"] = df["Name"].fillna(y)

In [6]:
df

     Name   Age
0    Amit  25.0
1     NaN  25.0
2    Amit   NaN
3  Snehal  28.0

In [7]:
df.isna().sum()

Name    1
Age     1
dtype: int64

In [8]:
for i in df.columns:
    if df[i].dtype  == "str":
        x = df[i].mode()[0]
        df[i] = df[i].fillna(x)
    else:
        y = df[i].mean()
        df[i] = df[i].fillna(y)

In [9]:
df

     Name   Age
0    Amit  25.0
1    Amit  25.0
2    Amit  26.0
3  Snehal  28.0

# Lable Encoding

In [10]:
df = pd.DataFrame({
    "Name":["Rahul", "Amit", "Sneha"],
    "Gender":["Male", "Male", "Female"],
    "City":["Pune", "Pune", "Mumbai"]}
)

In [11]:
df

    Name  Gender    City
0  Rahul    Male    Pune
1   Amit    Male    Pune
2  Sneha  Female  Mumbai

In [12]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

# df['Gender']=le.fit_transform(df['Gender'])

In [13]:
df

    Name  Gender    City
0  Rahul    Male    Pune
1   Amit    Male    Pune
2  Sneha  Female  Mumbai

In [14]:
# le.classes_

In [15]:
# by using loop

for i in df.columns:
    df[i]=le.fit_transform(df[i])
    print(i, le.classes_)

Name ['Amit' 'Rahul' 'Sneha']
Gender ['Female' 'Male']
City ['Mumbai' 'Pune']

In [16]:
df

   Name  Gender  City
0     1       1     1
1     0       1     1
2     2       0     0

# Assinment: train model on car sell data in only lable encoder