# KNN Algorithoum

Why is KNN called a lazy learner, and how does that affect prediction time versus training time?

How should we choose the best value of 
𝐾
K, and why can a very small or very large 
𝐾
K cause poor predictions?

Why is feature scaling essential for KNN when using Euclidean distance?

In what situations would Manhattan distance perform better than Euclidean distance?

How does the curse of dimensionality make KNN less effective with many features?

What happens when the nearest neighbors include a tie between two classes, and how should we handle it?

Why might distance-weighted KNN be better than giving every neighbor an equal vote?

How do outliers affect KNN classification and KNN regression?

How can we use cross-validation to select 
𝐾
K, distance metric, and weighting strategy together?

Why does KNN struggle with imbalanced datasets, and what methods can reduce this problem?

What is the difference between KNN classification and KNN regression in terms of prediction output?

How do decision boundaries change as 
𝐾
K increases?

When should we reduce dimensions using PCA before applying KNN?

How does the choice of distance metric change for categorical, text, or mixed-type data?

What data structures or approximate-nearest-neighbor methods make KNN faster for large datasets?

In [1]:
data = {
    "Area":[200,600,700,800,900,1000,1100,1200,1300,1400],
    "Bedrooms":[1,1,2,2,2,3,3,3,4,4],
    "Price":[30,35,40,45,50,55,60,65,72,80]
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   Area  Bedrooms  Price
0   200         1     30
1   600         1     35
2   700         2     40
3   800         2     45
4   900         2     50
5  1000         3     55
6  1100         3     60
7  1200         3     65
8  1300         4     72
9  1400         4     80

In [5]:
y = df[["Price"]]
X = df.drop(labels = ["Price"], axis = 1)

In [6]:
y

   Price
0     30
1     35
2     40
3     45
4     50
5     55
6     60
7     65
8     72
9     80

In [7]:
X

   Area  Bedrooms
0   200         1
1   600         1
2   700         2
3   800         2
4   900         2
5  1000         3
6  1100         3
7  1200         3
8  1300         4
9  1400         4

# Train Test Split

In [8]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.2, random_state = 42)

 # Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

xtrain_scaled = sc.fit_transform(xtrain)
xtest_scaled = sc.fit_transform(xtest)

In [10]:
xtrain_scaled

array([[ 0.25680509,  0.57735027],
       [-2.09112719, -1.73205081],
       [ 0.84378816,  0.57735027],
       [-0.62366951, -0.57735027],
       [ 1.43077123,  1.73205081],
       [-0.03668644, -0.57735027],
       [-0.33017798, -0.57735027],
       [ 0.55029663,  0.57735027]])

In [11]:
xtest_scaled

array([[ 1.,  1.],
       [-1., -1.]])

# Model

In [12]:
from sklearn.neighbors import KNeighborsRegressor

In [13]:
model = KNeighborsRegressor()

In [14]:
model.fit(xtrain_scaled,ytrain)

KNeighborsRegressor()

In [15]:
y_pred = model.predict(xtest_scaled)

In [16]:
y_pred

array([[62.],
       [44.]])

Evalute the Model

In [17]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

mae=mean_absolute_error(ytest, y_pred)
print("MAE: ",mae)

MAE:  9.5

In [18]:
0

1

2

3

4

5

6

7

Price

30

35

40

45

50

55

6q

65

pe here to search

SyntaxError: invalid decimal literal (2034808893.py, line 31)

In [19]:
1
2
3
4
5
6

6

In [20]:
# train
1
2
3
4

4

In [23]:
# test
5
6

6

In [ ]:
import numpy as np

In [27]:
# train

In [38]:
tr_m = np.mean([1,2,3,4])
tr_m

np.float64(2.5)

In [43]:
tr_s =np.std([1,2,3,4])
tr_s

np.float64(1.118033988749895)

In [33]:
# test

te_m = np.mean([5,6])

In [34]:
te_s = np.std([5,6])

In [42]:
# sc

for i in [1,2,3,4]:
    print((i - tr_m)/tr_s)

-1.3416407864998738
-0.4472135954999579
0.4472135954999579
1.3416407864998738

In [41]:
for i in [5,6]:
    print((i - te_m)/te_s)

-1.0
1.0

In [44]:
1
2
3
4
5
6

6

In [48]:
# train

1
2
3
4
train = [1,2,3,4]

In [49]:
# test

5
6

test = [5,6]

In [50]:
# mean and std


mean_tr = np.mean(train)
std_tr = np.std(train)

mean_te = np.mean(test)
std_te = np.std(test)

In [51]:
mean_tr - mean_te

np.float64(-3.0)

In [52]:
std_tr - std_te

np.float64(0.6180339887498949)

In [60]:
for i in train:
    print(f"train: {i}:", (i - mean_tr)/std_tr)

train: 1: -1.3416407864998738
train: 2: -0.4472135954999579
train: 3: 0.4472135954999579
train: 4: 1.3416407864998738

In [63]:
for j in test:
    print(f"test: {j}:", (j - mean_tr)/std_tr)

test: 5: 2.23606797749979
test: 6: 3.1304951684997055

In [64]:
data = [1,2,3,4,5,6]

In [65]:
for i in data:
    print(f"train: {i}", (i - np.mean(data))/np.std(data))

train: 1 -1.4638501094227998
train: 2 -0.8783100656536799
train: 3 -0.29277002188455997
train: 4 0.29277002188455997
train: 5 0.8783100656536799
train: 6 1.4638501094227998

In [67]:
x_tr, x_te= train_test_split(data, test_size = 0.2)

In [70]:
np.mean(x_tr)

np.float64(3.5)

In [69]:
npx_te

[6, 1]